-- Basic config
require("core.mappings")
require("core.plugins")
require("core.theme")
require("core.configs")

-- Plugins config
require("plugins.telescope")
require("plugins.mason")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.nullls")
require("plugins.lualine")
require("plugins.gitsigns")
require("plugins.treesitter")
require("plugins.outline")
require("plugins.autopairs")
require("plugins.comments")
require("plugins.autotag")
require("plugins.buffline")
require("plugins.neotree")
require("plugins.whichkey")
require("plugins.ng")
require("plugins.neodev")
require("plugins.toggleterm")
require("plugins.bqf")
require("plugins.leap")
